Add a Bash-based fallback for waiting for and tracking connection.
It's set up to only trigger if the Python-based script fails.

diff --git a/ci_connection/action.yaml b/ci_connection/action.yaml
--- a/ci_connection/action.yaml
+++ b/ci_connection/action.yaml
@@ -17,19 +17,29 @@ inputs:
   halt-dispatch-input:
     description: 'Should the action wait for user connection from workflow_dispatch?'
     required: false
-    default: "no"
+    default: no
 runs:
-  using: "composite"
+  using: composite
   steps:
-  - name: Wait for connection (conditionally)
-    shell: bash
-    env:
-      PYTHONUNBUFFERED: 1
-      HALT_DISPATCH_INPUT: ${{ inputs.halt-dispatch-input }}
-    # The calling workflow shouldn't fail in case this step does
-    continue-on-error: true
-    run: |
-      # Pick an existing Python alias
-      python_bin=$(which python3 2>/dev/null || which python)
-      # Wait for the connection, if a halt was requested via a label/input
-      "$python_bin" "$GITHUB_ACTION_PATH/wait_for_connection.py"
+
+    # First try to set up waiting with Python, as it has some QoL features, like mirroring the `env` state, etc.
+    - name: Wait for connection
+      id: primary
+      shell: bash
+      continue-on-error: true
+      env:
+        PYTHONUNBUFFERED: 1
+        HALT_DISPATCH_INPUT: ${{ inputs.halt-dispatch-input }}
+      run: |
+        set +e
+        python_bin=$(which python3 2>/dev/null || which python)
+        "$python_bin" "$GITHUB_ACTION_PATH/wait_for_connection.py"
+        set -e
+        echo "exit_code=$?" >>"$GITHUB_OUTPUT"
+
+    # If Python fails, or isn't available, fall back to using Bash for a simpler keep-alive loop
+    - name: Wait for connection (shell-based fallback in case Python is not available, or fails)
+      if: ${{ steps.primary.outputs.exit_code != '0' }}
+      continue-on-error: true
+      shell: bash
+      run: bash "$GITHUB_ACTION_PATH/wait_for_connection_fallback.sh"
